services:
  - type: web
    name: carbonflow-backend
    env: python
    plan: free
    rootDir: backend
    buildCommand: "pip install -r requirements.txt && python manage.py migrate"
    startCommand: "gunicorn carbonflow.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: "3.12.3"
